AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  ClamAV-scanner-Lambda

  S3 Antivirus scanner with ClamAV Lambda

#   ___                         _
#  | _ \__ _ _ _ __ _ _ __  ___| |_ ___ _ _ ___
#  |  _/ _` | '_/ _` | '  \/ -_)  _/ -_) '_(_-<
#  |_| \__,_|_| \__,_|_|_|_\___|\__\___|_| /__/

Parameters:
  Env:
    Description: Environment type
    Default: uat
    Type: String
    AllowedValues: [prod, dev, uat]
    ConstraintDescription: must specify prod, dev, or uat.
  S3LambdaClamAvBucketName:
    Type: String
    Default: "storage"
    MinLength: 1
    Description: "AWS S3 bucket name which stores ClamAV Lambda zip file"
  S3ClamAvDefinitionBucketName:
    Type: String
    Default: "storage"
    MinLength: 1
    Description: "AWS S3 bucket name to which stores ClamAV virus definition files"
  S3ClamAvDefinitionBucketPath:
    Type: String
    Default: "clamav"
    Description: "AWS S3 bucket path to folder that stores ClamAV virus definition files"
  S3TargetVirusScanBucketName:
    Type: String
    Default: "target-bucket"
    MinLength: 1
    Description: "AWS S3 bucket name to which stores a file to be scanned (If there are more than 1 bucket, please manually add ARN in Lambda virus scanner role)"
  S3TargetVirusScanBucketPath:
    Type: String
    Description: "AWS S3 bucket path to folder which stores a file to be scanned"

#   __  __                _
#  |  \/  |__ _ _ __ _ __(_)_ _  __ _ ___
#  | |\/| / _` | '_ \ '_ \ | ' \/ _` (_-<
#  |_|  |_\__,_| .__/ .__/_|_||_\__, /__/
#              |_|  |_|         |___/

Mappings:
  # Zip file of Python Lambda for image classification model
  ClamAVZipFile:
    dev:
      name: "clamav_lambda.zip"
    uat:
      name: "clamav_lambda.zip"
    prod:
      name: "clamav_lambda.zip"

#    ___             _ _ _   _
#   / __|___ _ _  __| (_) |_(_)___ _ _  ___
#  | (__/ _ \ ' \/ _` | |  _| / _ \ ' \(_-<
#   \___\___/_||_\__,_|_|\__|_\___/_||_/__/

Conditions:
  HasS3ClamAvDefinitionBucketPath:
    !Not [!Equals ["", !Ref S3ClamAvDefinitionBucketPath]]
  HasS3TargetVirusScanBucketPath:
    !Not [!Equals ["", !Ref S3TargetVirusScanBucketPath]]

#   ___
#  | _ \___ ___ ___ _  _ _ _ __ ___ ___
#  |   / -_|_-</ _ \ || | '_/ _/ -_|_-<
#  |_|_\___/__/\___/\_,_|_| \__\___/__/

Resources:
  #   _
  #  (_)__ _ _ __
  #  | / _` | '  \
  #  |_\__,_|_|_|_|

  # IAM

  #             _ _
  #   _ __  ___| (_)__ _  _
  #  | '_ \/ _ \ | / _| || |
  #  | .__/\___/_|_\__|\_, |
  #  |_|               |__/

  ## Policy
  ClamAvAccessLog:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: AccessLog
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action: "logs:*"
            Resource: "arn:aws:logs:*:*:*"
      Roles:
        - !Ref ClamAvLambdaVirusScannerRole
        - !Ref ClamAvLambdaVirusDefinitionUpdaterRole

  ClamAvGetDocumentS3LambdaClamAvZip:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: GetObjectFromS3LambdaClamAvZip
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action:
              - "s3:GetObject"
              - "s3:GetObjectVersion"
            Resource:
              - !Sub arn:aws:s3:::${S3LambdaClamAvBucketName}/*
      Roles:
        - !Ref ClamAvLambdaVirusScannerRole
        - !Ref ClamAvLambdaVirusDefinitionUpdaterRole

  ClamAvPutDocumentS3ClamAvDefinition:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: PutObjectToS3ClamAvDefinition
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action:
              - "s3:PutObject"
            Resource:
              - !If
                - HasS3ClamAvDefinitionBucketPath
                - !Sub arn:aws:s3:::${S3ClamAvDefinitionBucketName}/${S3ClamAvDefinitionBucketPath}/*
                - !Sub arn:aws:s3:::${S3ClamAvDefinitionBucketName}/*
      Roles:
        - !Ref ClamAvLambdaVirusDefinitionUpdaterRole

  ClamAvGetDocumentS3ClamAvDefinition:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: GetObjectFromS3ClamAvDefinition
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action:
              - "s3:GetObject"
              - "s3:GetObjectVersion"
            Resource:
              - !If
                - HasS3ClamAvDefinitionBucketPath
                - !Sub arn:aws:s3:::${S3ClamAvDefinitionBucketName}/${S3ClamAvDefinitionBucketPath}/*
                - !Sub arn:aws:s3:::${S3ClamAvDefinitionBucketName}/*
      Roles:
        - !Ref ClamAvLambdaVirusScannerRole

  #           _
  #   _ _ ___| |___
  #  | '_/ _ \ / -_)
  #  |_| \___/_\___|

  ## Role
  ClamAvLambdaVirusScannerRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub ClamAvLambdaVirusScannerRoleFor${Env}
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: LambdaGetAndPutScannedFile
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - "s3:PutObject"
                  - "s3:PutObjectTagging"
                  - "s3:GetObject"
                  - "s3:GetObjectVersion"
                Resource:
                  - !If
                    - HasS3TargetVirusScanBucketPath
                    - !Sub arn:aws:s3:::${S3TargetVirusScanBucketName}/${S3TargetVirusScanBucketPath}/*
                    - !Sub arn:aws:s3:::${S3TargetVirusScanBucketName}/*
      MaxSessionDuration: 3600
      Path: /

  ClamAvLambdaVirusDefinitionUpdaterRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub ClamAvLambdaVirusDefinitionUpdaterRoleFor${Env}
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action: sts:AssumeRole
      MaxSessionDuration: 3600
      Path: /

  #    ___ _             ___      __    _      _      ___             _
  #   / __| |___ _  _ __| \ \    / /_ _| |_ __| |_   | __|_ _____ _ _| |_
  #  | (__| / _ \ || / _` |\ \/\/ / _` |  _/ _| ' \  | _|\ V / -_) ' \  _|
  #   \___|_\___/\_,_\__,_| \_/\_/\__,_|\__\__|_||_| |___|\_/\___|_||_\__|

  ClamAvScheduledRule:
    Type: AWS::Events::Rule
    Properties:
      Description: ScheduledRule to invoke virus definition updater lambda
      ScheduleExpression: "cron(0 */6 * * ? *)" # every 6 hours
      State: ENABLED
      Targets:
        - Arn: !GetAtt ClamAvLambdaVirusDefinitionUpdater.Arn
          Id: UpdateVirusDefinition

  ClamAvPermissionForEventsToInvokeLambda:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref ClamAvLambdaVirusDefinitionUpdater
      Action: lambda:InvokeFunction
      Principal: events.amazonaws.com
      SourceArn: !GetAtt ClamAvScheduledRule.Arn

  #   _            _        _
  # | |__ _ _ __ | |__  __| |__ _
  # | / _` | '  \| '_ \/ _` / _` |
  # |_\__,_|_|_|_|_.__/\__,_\__,_|

  ClamAvLambdaVirusScanner:
    Type: AWS::Lambda::Function
    Properties:
      Handler: antivirusApp.lambdaHandleEvent
      Runtime: nodejs8.10
      Description: "ClamAvLambdaVirusScanner Lambda"
      MemorySize: 1024
      Timeout: 300
      Role: !GetAtt ClamAvLambdaVirusScannerRole.Arn
      Code:
        S3Bucket: !Ref S3LambdaClamAvBucketName
        S3Key: !FindInMap [ClamAVZipFile, !Ref Env, name]
      Environment:
        Variables:
          ENV: !Ref Env
          CLAMAV_BUCKET_NAME: !Ref S3ClamAvDefinitionBucketName
          PATH_TO_AV_DEFINITIONS: !Ref S3ClamAvDefinitionBucketPath

  ClamAvLambdaVirusDefinitionUpdater:
    Type: AWS::Lambda::Function
    Properties:
      Handler: downloadDefinitionApp.lambdaHandleEvent
      Runtime: nodejs8.10
      Description: "ClamAvLambdaVirusDefinitionUpdater Lambda"
      MemorySize: 1024
      Timeout: 300
      Role: !GetAtt ClamAvLambdaVirusDefinitionUpdaterRole.Arn
      Code:
        S3Bucket: !Ref S3LambdaClamAvBucketName
        S3Key: !FindInMap [ClamAVZipFile, !Ref Env, name]
      Environment:
        Variables:
          ENV: !Ref Env
          CLAMAV_BUCKET_NAME: !Ref S3ClamAvDefinitionBucketName
          PATH_TO_AV_DEFINITIONS: !Ref S3ClamAvDefinitionBucketPath
